[simplematrixbotlib.config]
description = "This is a simple matrix bot library created by liuyang for audio recognition and text to AI models like (chatgpt | mdjurney)"

homeserver = "https://matrix.liuy.site"
username = ""
password = ""
login_token = ""
access_token = ""
#OPEN_AI_KEY = ""# key from open AI
ENABLE_ENCRYPTION = "True"
OPEN_AI_KEY = ''# key from open AI
REPLICATE_API_TOKEN = ""