[simplematrixbotlib.config]
description = "This is a simple matrix bot library created by liuyang for audio recognition and text to AI models like (chatgpt | mdjurney)"

homeserver = "https://matrix.liuy.site"
username = "liuy"
password = ""
login_token = ""
access_token = "syt_bGl1eQ_acyWZAGrDSGfNjcqCncL_1QAo40"
#OPEN_AI_KEY = ""# key from open AI
ENABLE_ENCRYPTION = "True"
OPEN_AI_KEY = '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'# key from open AI
REPLICATE_API_TOKEN = '2c58cf760a1d7b056096f84bbb7bb14938ff71b5'